-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 12:46:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gamerail
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gamerail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamerail` DEFAULT CHARACTER SET utf8 ;
USE `gamerail` ;

-- -----------------------------------------------------
-- Table `gamerail`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerail`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `adminUnlock` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerail`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerail`.`video` (
  `idvideo` INT NOT NULL AUTO_INCREMENT,
  `video` BLOB NOT NULL,
  PRIMARY KEY (`idvideo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerail`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerail`.`foto` (
  `idfoto` INT NOT NULL AUTO_INCREMENT,
  `foto` BLOB NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idfoto`, `user_id`),
  INDEX `fk_foto_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_foto_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gamerail`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerail`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerail`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `foto` BLOB NULL,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `foto_id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_categoria_foto1_idx` (`foto_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `gamerail`.`foto` (`idfoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerail`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerail`.`jogos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `vendas` INT NULL,
  `sobre` VARCHAR(500) NULL,
  `dev_id` INT NOT NULL,
  `dist_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `foto_id` INT NOT NULL,
  `valor` DECIMAL(2) NULL,
  PRIMARY KEY (`id`, `dev_id`, `dist_id`, `video_id`, `categoria_id`, `foto_id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_jogos_user1_idx` (`dev_id` ASC) VISIBLE,
  INDEX `fk_jogos_user2_idx` (`dist_id` ASC) VISIBLE,
  INDEX `fk_jogos_video1_idx` (`video_id` ASC) VISIBLE,
  INDEX `fk_jogos_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_jogos_foto1_idx` (`foto_id` ASC) VISIBLE,
  CONSTRAINT `fk_jogos_user1`
    FOREIGN KEY (`dev_id`)
    REFERENCES `gamerail`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_user2`
    FOREIGN KEY (`dist_id`)
    REFERENCES `gamerail`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `gamerail`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `gamerail`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `gamerail`.`foto` (`idfoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gamerail`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerail`.`compras` (
  `id` INT NOT NULL,
  `dataBuy` DATE NOT NULL,
  `user_id` INT NOT NULL,
  `jogos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `jogos_id`),
  INDEX `fk_compras_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_compras_jogos1_idx` (`jogos_id` ASC) VISIBLE,
  CONSTRAINT `fk_compras_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gamerail`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_jogos1`
    FOREIGN KEY (`jogos_id`)
    REFERENCES `gamerail`.`jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
